---
title: "OM7 Market Research"
# execute: 
#   freeze: auto
---

Welcome to our module Market Research (337094)! 👋  

>The numbers have no way of speaking for themselves. We speak for them. Nate Silver

This page contains an outline of the topics and content for the semester. 

:::{.callout-note appearance="minimal"}
Note that our schedule will be updated as the semester progresses.
:::


[Moodle-course](https://moodle.hdm-stuttgart.de/course/view.php?id=21927)

---


```{r}
#| echo: false
#| message: false
#| warning: false
# Install required packages if not already installed
library(googlesheets4)
library(gt)
library(tidyverse)
gs4_deauth()
d <- read_sheet("https://docs.google.com/spreadsheets/d/1CRW5o9ZbL4Dbs04G5zT8dlSdMQ2qN5IDRQEu7srH2zM/edit?usp=sharing")
```



```{r}
#| echo: false

d |>
  #filter(!is.na(session)) |>
  select(-dow, -session) |>
  mutate(date = as.Date(date)) |>
  relocate(lecture, .after = materials) |>
  gt() |>
  fmt_date(date, date_style = 31) |>
  sub_missing(columns = c(week, prepare, topic, materials, lecture), missing_text = "") |>
  cols_align(
    align = "center", 
    columns = c(week)
  ) |>
  cols_align(
    align = "right", 
    columns = c(date)
  ) |>
  cols_align(
    align = "left", 
    columns = c(topic, prepare, materials, lecture)
  ) |>
  tab_style(
    style = cell_borders(
      sides = "right",
      color = "#D3D3D3",
      style = "solid"
    ),
    locations = cells_body(
      columns = c(date, topic, prepare, materials)
    )
  ) |>
  fmt_markdown(
    columns = c(topic, prepare, materials, lecture)
  ) |>
  cols_width(
    week ~ px(45),
    date ~ px(100), 
    prepare ~ px(100),
    topic ~ px(300),
    materials ~ px(150),
    lecture ~ px(300)
  ) |>
  cols_label_with(fn = function(x) {
      janitor::make_clean_names(x, case = "title") |>
        toupper() |>
        stringr::str_replace_all("^|$", "**") |>
        md()
    }) |>
  tab_options(table.font.size = 13) |>
  opt_row_striping()
```